export default [
  {
    title: 'Songs over Time by BPM',
    subtitle: 'my music collection over time by bpm',
    date: 'Jul 10, 2017',
    url: 'bpm-3',
    imageFilename: 'bpm_visual_3_ss.png',
  },
  {
    title: 'Fantasy Basketball Ranks \'16',
    subtitle: 'top basketball players in fantasy scoring in 2016',
    date: 'Oct 21, 2016',
    url: 'bball-ranks-2',
    imageFilename: 'bball_ranks_2016_ss.png',
  },
  {
    title: 'BPM Visual Revisited',
    subtitle: 'my music collection sorted by bpm',
    date: 'Sep 14, 2016',
    url: 'bpm-2',
    imageFilename: 'bpm_visual_2_ss.png',
  },
  {
    title: 'DC Demographics',
    subtitle: 'breakdown of dc by demographic',
    date: 'Jun 18, 2015',
    url: 'dc-demographics',
    imageFilename: 'dc_demographics_ss.png',
  },
  {
    title: 'How Teams Do In March Madness',
    subtitle: 'tournament performance in the last 30 years',
    date: 'Mar 19, 2015',
    url: 'march-madness',
    imageFilename: 'march_madness_ss.png',
  },
  {
    title: 'Fantasy Football Revisited',
    subtitle: 'how well fantasy football players performed',
    date: 'Dec 25, 2014',
    url: 'fantasy-football-performance',
    imageFilename: 'ff_performance_ss.png',
  },
  {
    title: 'Facebook Friend Network',
    subtitle: 'force layout diagram of my facebook friends',
    date: 'Nov 21, 2014',
    url: 'facebook-network',
    imageFilename: 'fb_force_ss.png',
  },
  {
    title: 'BPM Visual',
    subtitle: 'my music collection sorted by bpm',
    date: 'Nov 11, 2014',
    url: 'bpm',
    imageFilename: 'bpm_visual_ss.png',
  },
  {
    title: 'DC Snowfall',
    subtitle: 'yearly snowfall in dc',
    date: 'Nov 10, 2014',
    url: 'dc-snowfall',
    imageFilename: 'dc_snowfall_ss.png',
  },
  {
    title: 'Fantasy Basketball Ranks',
    subtitle: 'the top basketball players in fantasy scoring',
    date: 'Oct 28, 2014',
    url: 'bball-ranks',
    imageFilename: 'bball_ranks_ss.png',
  },
  {
    title: 'TV Show Viewership',
    subtitle: 'a look at the ratings of recent popular tv shows',
    date: 'Oct 12, 2014',
    url: 'tv-show-viewership',
    imageFilename: 'tv_shows_ss.png',
  },
  {
    title: 'Income Thresholds',
    subtitle: 'class division in the u.s.',
    date: 'Aug 19, 2014',
    url: 'income',
    imageFilename: 'income_ss.png',
  },
];
